
import React from 'react';
import type { EvidenceSource } from '../types';

interface EvidencePanelProps {
  sources: EvidenceSource[];
  confidenceScore: number;
  placesApiMatch: boolean;
}

const sourceTypeLabels: Record<string, { label: string; icon: string }> = {
  google_places: { label: 'Google Places', icon: '📍' },
  google_maps: { label: 'Google Maps', icon: '🗺️' },
  news_article: { label: 'News Article', icon: '📰' },
  directory: { label: 'Directory Listing', icon: '📋' },
  community_report: { label: 'Community Report', icon: '👥' },
  indigenous_directory: { label: 'Indigenous Directory', icon: '🪶' },
  user_submission: { label: 'User Submission', icon: '👤' },
  web_search: { label: 'Web Search', icon: '🌐' },
};

export const EvidencePanel: React.FC<EvidencePanelProps> = ({ sources, confidenceScore, placesApiMatch }) => {
  if (sources.length === 0 && !placesApiMatch) {
    return (
      <div className="bg-amber-50 border border-amber-200 rounded-2xl p-6">
        <div className="flex items-start gap-3">
          <span className="text-xl">⚠️</span>
          <div>
            <h4 className="font-bold text-amber-800 text-sm mb-1">No independent verification available</h4>
            <p className="text-amber-700 text-xs leading-relaxed">
              This listing was generated by AI and has not been independently verified against maps, directories, or other sources. It may not exist in the real world.
            </p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-white border border-stone-200 rounded-2xl p-6">
      <div className="flex items-center justify-between mb-4">
        <h4 className="font-black text-stone-900 text-sm uppercase tracking-wider flex items-center gap-2">
          <svg className="w-4 h-4 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
          </svg>
          Evidence Sources
        </h4>
        <div className="flex items-center gap-2">
          <div className="w-16 h-2 bg-stone-100 rounded-full overflow-hidden">
            <div
              className={`h-full rounded-full transition-all ${
                confidenceScore >= 0.6 ? 'bg-blue-600' : confidenceScore >= 0.3 ? 'bg-amber-500' : 'bg-red-400'
              }`}
              style={{ width: `${Math.min(confidenceScore * 100, 100)}%` }}
            />
          </div>
          <span className="text-xs font-bold text-stone-500">{Math.round(confidenceScore * 100)}%</span>
        </div>
      </div>

      <div className="space-y-3">
        {sources.map((source, idx) => {
          const typeInfo = sourceTypeLabels[source.type] || { label: source.type, icon: '📄' };
          return (
            <div key={idx} className="flex items-start gap-3 p-3 bg-stone-50 rounded-xl">
              <span className="text-lg flex-shrink-0">{typeInfo.icon}</span>
              <div className="flex-grow min-w-0">
                <p className="text-sm font-bold text-stone-800">{source.name}</p>
                <div className="flex items-center gap-2 mt-1">
                  <span className="text-[10px] font-bold text-stone-400 uppercase tracking-wider">{typeInfo.label}</span>
                  {source.date && (
                    <span className="text-[10px] text-stone-400">{source.date}</span>
                  )}
                </div>
                {source.url && (
                  <a
                    href={source.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-xs text-blue-600 hover:underline mt-1 block truncate"
                  >
                    {source.url}
                  </a>
                )}
              </div>
            </div>
          );
        })}
      </div>

      <p className="text-[10px] text-stone-400 mt-4 leading-relaxed">
        Derived from historical/third-party sources; may be inaccurate; not affiliated with Google Business Profile.
      </p>
    </div>
  );
};
